### ISSUE TITLE
Can't establish socket connection when not accessed via localhost

### ISSUE THREAD

**Issue by jhnns** [peerigon/nof5#1]
This one is probably easy to fix. The socket connection can't be established when I try to access the test page via another IP than localhost (e.g. when you're using a virtual machine). This is because socket.io tries to connect to localhost nevertheless which IP is used. 

I think the best way to fix this would be to use the location-object in the browser to determine the connection's destination.

**Comment by topa** [comment]
Should be fixed now with commit #4caa25144f
