### ISSUE TITLE
xunit-support

### ISSUE THREAD

**Issue by topa** [peerigon/nof5#6]
It should be possible to run the tests on a set of browsers and write the result to a xunit-file.

**Comment by matthaias** [comment]
On the Jenkins Server?

**Comment by topa** [comment]
xunit-support for nof5, so that can jenkins is able to handle it;)

**Comment by matthaias** [comment]
Is it a problem at the moment? The mocha tests are running with the xunit reporter too and jenkins is working with that file. Try it and if you have a problem with it tell me again, ok?

**Comment by topa** [comment]
Hey @matthaias !

We're here in the nof5 repo. It is all about running tests on clients. The xunit reporter from mocha does not work on the client site, does it? 
Check out the first words from [Readme.md](https://github.com/peerigon/nof5/blob/master/README.md) to get a short description about nof5. 
But I can explain it to you tomorrow.

**Comment by topa** [comment]
I've thought about the interface for xunit-file support:
- nof5 should write a xunit file if an option <code>--x</code> or <code>--xunit</code> is given.
- If <code>--x</code> or <code>--xunit</code> are given without a path nof5 should write the xunit-file into <code>process.cwd()</code> else to the given path.

But there is a problem, because nof5 is not able to know **which** clients must connect and send their results to complete the test. I don't see any other way than passing this information to nof5. I think this should be done with a special hook, probably something like: <code>nof5.clients.hook.js</code>. This is similar to the other existing hooks, e.g. for passing additional middleware for the browserify bundler. According to the current convention for hooks the <code>nof5.clients.hook.js</code> might looks like this:
- If there is a file named <code>nof5.client.hook.js</code> in the test folder, than this file will be automatically used.
- If there is an explicit path given than by an option <code>--c</code> or <code>--clients</code> than this file will be used.
- The file should be a module exporting a function <code>.use()</code>
- The <code>.use()</code> function returns an <code>{}</code> containing options.
- These could be useful options:
  - clients: ["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.79 Safari/537.1", "Mozilla/5.0 (X11; Linux x86_64; rv:14.0) Gecko/20100101 Firefox/14.0.1", "and so on"..]
  - timeout: number
- I recommend to use the <code>navigator.userAgent</code> string as this will make a client unique

@matthaias what do you think about this?
